/**
 * Worker entry: OpenNext's generated handler for every request, plus the
 * nightly jobs that vercel.json runs as Vercel crons.
 *
 * The cron does not reimplement anything. It calls the same two route
 * handlers Vercel calls, through the same fetch handler, with the same
 * CRON_SECRET bearer token, so the auth check, the fail closed rule and the
 * job logic stay in one place: app/api/cron/*.
 *
 * A failed job is logged, emailed to ADMIN_EMAIL through Resend when the key
 * is set, and then thrown so the invocation shows as failed under the
 * Worker's cron events. A silent miss is how the cleanup job stayed broken
 * for weeks, so a failure has to reach a person.
 *
 * Excluded from tsconfig because it imports a file that only exists after
 * `npx opennextjs-cloudflare build`. Wrangler bundles it with esbuild.
 */

// @ts-expect-error generated by `npx opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";

interface Env {
  CRON_SECRET?: string;
  RESEND_API_KEY?: string;
  RESEND_FROM_EMAIL?: string;
  ADMIN_EMAIL?: string;
  [key: string]: unknown;
}

interface Ctx {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

interface Controller {
  cron: string;
  scheduledTime: number;
}

// The canonical host. The request never leaves the Worker, handler.fetch is
// a direct call, so this only has to be a host the app treats as its own.
const ORIGIN = "https://tsakanisessions.co.za";

const NIGHTLY_JOBS = ["/api/cron/cleanup-orders", "/api/cron/finalize-events"];

async function runJob(path: string, env: Env, ctx: Ctx): Promise<string | null> {
  try {
    const res: Response = await handler.fetch(
      new Request(`${ORIGIN}${path}`, {
        headers: {
          authorization: `Bearer ${env.CRON_SECRET ?? ""}`,
          "user-agent": "tsakani-worker-cron",
        },
      }),
      env,
      ctx
    );
    const body = (await res.text()).slice(0, 500);
    if (!res.ok) return `${path} answered ${res.status}: ${body}`;
    console.log(`cron ${path} ${res.status} ${body}`);
    return null;
  } catch (e) {
    return `${path} threw: ${e instanceof Error ? e.message : String(e)}`;
  }
}

async function alertByEmail(env: Env, failures: string[], when: string): Promise<void> {
  if (!env.RESEND_API_KEY || !env.ADMIN_EMAIL) {
    console.error("cron alert not emailed: RESEND_API_KEY or ADMIN_EMAIL is not set");
    return;
  }
  try {
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        authorization: `Bearer ${env.RESEND_API_KEY}`,
        "content-type": "application/json",
      },
      body: JSON.stringify({
        from: env.RESEND_FROM_EMAIL || "Tsakani Sessions <onboarding@resend.dev>",
        to: [env.ADMIN_EMAIL],
        subject: "Tsakani nightly job failed",
        text: `The ${when} run on the Cloudflare Worker failed.\n\n${failures.join("\n\n")}\n\nCheck the Worker's logs and cron events in the Cloudflare dashboard.`,
      }),
    });
    if (!res.ok) console.error(`cron alert email refused: ${res.status} ${await res.text()}`);
  } catch (e) {
    console.error(`cron alert email failed: ${e instanceof Error ? e.message : String(e)}`);
  }
}

const worker = {
  fetch: handler.fetch,

  async scheduled(controller: Controller, env: Env, ctx: Ctx): Promise<void> {
    const failures: string[] = [];
    // One after the other, and both always run: finalize-events does not
    // depend on cleanup-orders succeeding.
    for (const path of NIGHTLY_JOBS) {
      const failure = await runJob(path, env, ctx);
      if (failure) failures.push(failure);
    }
    if (failures.length > 0) {
      const when = new Date(controller.scheduledTime).toISOString();
      console.error(`cron ${controller.cron} failed at ${when}\n${failures.join("\n")}`);
      await alertByEmail(env, failures, when);
      throw new Error(`nightly jobs failed: ${failures.length} of ${NIGHTLY_JOBS.length}`);
    }
  },
};

export default worker;
